# OCRNet_W48.yml
train_dataset:
  type: Dataset
  dataset_root: dataset
  train_path: dataset/train.txt
  num_classes: 2
  transforms:
    - type: RandomHorizontalFlip
    - type: RandomVerticalFlip
    - type: ResizeStepScaling
    - type: RandomPaddingCrop
      im_padding_value: [0, 0, 0]
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: dataset
  val_path: dataset/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val


batch_size: 12
iters: 20000

model:
  type: OCRNet
  backbone:
    type: HRNet_W48
  pretrained: ./model_pretained_bcebos.pdparams
  num_classes: 2
  backbone_indices: [0]

optimizer:
  type: sgd

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: BCELoss
        - type: DiceLoss
      coef: [0.8, 0.2]
    - type: MixedLoss
      losses:
        - type: BCELoss
        - type: DiceLoss
      coef: [0.8, 0.2]
  coef: [1, 0.4]